namespace jmespath.lexer;
public enum TokenType {
    E_UNRECOGNIZED = 0,
    T_WHITESPACE = 1,
    error=2,
    EOF=3,
    T_AND=4,
    T_OR=5,
    T_NOT=6,
    T_COLON=7,
    T_COMMA=8,
    T_DOT=9,
    T_PIPE=10,
    T_EQ=11,
    T_GT=12,
    T_GE=13,
    T_LT=14,
    T_LE=15,
    T_NE=16,
    T_FILTER=17,
    T_FLATTEN=18,
    T_STAR=19,
    T_CURRENT=20,
    T_ETYPE=21,
    T_NUMBER=22,
    T_LSTRING=23,
    T_QSTRING=24,
    T_RSTRING=25,
    T_USTRING=26,
    T_LBRACE=27,
    T_RBRACE=28,
    T_LBRACKET=29,
    T_RBRACKET=30,
    T_LPAREN=31,
    T_RPAREN=32,

    T_MAX = 33,
};

