name: 🚀 release

on:
  release:
    types: [published]

jobs:
  release:
    name: 🚀 release
    runs-on: windows-latest
    permissions:
      contents: read
      id-token: write # enable GitHub OIDC token issuance for this job

    steps:
      - name: 📚 checkout
        uses: actions/checkout@v4

      - name: ⚙️ Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "6.0.x"

      - name: 🔓 Decrypt strong-name key
        run: bin/EncryptDecryptFile.PS1
        shell: pwsh
        env:
          SN_PASSPHRASE: ${{ secrets.SN_PASSPHRASE }}
          SN_SALT: ${{ secrets.SN_SALT }}
          SN_INIT: ${{ secrets.SN_INIT }}

      - name: 📦 Restore dependencies
        run: dotnet restore pack/pack.sln

      - name: 🔨 Build
        run: dotnet build pack/pack.sln --configuration Release --no-restore

      # Use the ambient GitHub token to login to NuGet and retrieve an API key
      - name: 🔑 NuGet login (OIDC → temp API key)
        uses: NuGet/login@v1
        id: login
        with:
          # Secret is your NuGet username, e.g. 'jmespath-community'
          user: ${{ secrets.NUGET_USER }}
