name: 🚀 release

on:
  release:
    types: [published]

jobs:
  release:
    name: 🚀 release
    runs-on: windows-latest
    steps:
      - name: 📚 checkout
        uses: actions/checkout@v4

      - name: ⚙️ Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "6.0.x"

      - name: 📦 Restore dependencies
        run: dotnet restore pack/pack.sln

      - name: 🔨 Build
        run: dotnet build pack/pack.sln --configuration Release --no-restore
